In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv('input/train.csv')
size = df.loc[df['track_id'].idxmax()]['track_id']
print(size)
playlistsForTrack = np.empty([size], dtype=set)
for i in range(size):
    playlistsForTrack[i] = set(df[df['track_id']==i]['playlist_id'])
bestSimilarTracks = np.empty((size), dtype=object)
print(size)
print(bestSimilarTracks)
for i in range(size):
    print(i)
    bestSimilarTracks[i] = np.empty((size, 2), dtype=object)
    bestSimilarTracks[i][i] = [0,i]
    for j in range(i):
        similarity = len(playlistsForTrack[i] & playlistsForTrack[j])/min((len(playlistsForTrack[i]), len(playlistsForTrack[j])))
        bestSimilarTracks[i][j] = [-1*similarity, j]
    for j in range(i+1, size):
        similarity = len(playlistsForTrack[i] & playlistsForTrack[j])/min((len(playlistsForTrack[i]), len(playlistsForTrack[j])))
        bestSimilarTracks[i][j] = [-1*similarity, j]
    bestSimilarTracks[i] = np.partition(bestSimilarTracks[i], 10, axis=0)[0:10]
    bestSimilarTracks[i] = bestSimilarTracks[i][bestSimilarTracks[i][:,0] !=0]#[:,1]
    bestSimilarTracks[i][:,0] = -1*bestSimilarTracks[i][:,0]
    print(bestSimilarTracks[i])

20634
20634
[None None None ... None None None]
0
[[0.3333333333333333 0]
 [0.3076923076923077 1]
 [0.3076923076923077 2]
 [0.2857142857142857 3]
 [0.2857142857142857 4]
 [0.2692307692307692 5]
 [0.2692307692307692 6]
 [0.2692307692307692 7]
 [0.2692307692307692 8]
 [0.26666666666666666 9]]
1
[[1.0 0]
 [1.0 1]
 [1.0 2]
 [0.7272727272727273 3]
 [0.5294117647058824 4]
 [0.5294117647058824 5]
 [0.5 6]
 [0.5 7]
 [0.5 8]
 [0.5 9]]
2
[[1.0 0]
 [0.5 1]
 [0.5 2]
 [0.5 3]
 [0.5 4]
 [0.5 5]
 [0.5 6]
 [0.5 7]
 [0.5 8]
 [0.5 9]]
3
[[0.625 0]
 [0.5714285714285714 1]
 [0.5 2]
 [0.375 3]
 [0.375 4]
 [0.25 5]
 [0.25 6]
 [0.25 7]
 [0.25 8]
 [0.25 9]]
4
[[1.0 0]
 [0.9166666666666666 1]
 [0.9166666666666666 2]
 [0.9166666666666666 3]
 [0.9166666666666666 4]
 [0.9166666666666666 5]
 [0.9166666666666666 6]
 [0.9 7]
 [0.8333333333333334 8]
 [0.8333333333333334 9]]
5
[[1.0 0]
 [0.5 1]
 [0.5 2]
 [0.5 3]
 [0.4 4]
 [0.34285714285714286 5]
 [0.3333333333333333 6]
 [0.3333333333333333 7]
 [0.3333333333333333 8]
 

KeyboardInterrupt: 

In [20]:
df1 = pd.read_csv('input/target_playlists.csv')

In [21]:
playlists = np.array(df1['playlist_id'])
print(playlists)

[    7    25    29 ... 50416 50417 50424]


In [24]:
for playlist in playlists:
    tracks = np.array(df[df['playlist_id']==playlist]['track_id'])
    best = {}
    for track in tracks:
        for similar in bestSimilarTracks[track]:
            if similar[1] in best:
                best[similar[1]]+=similar[0]
            else:
                best[similar[1]]=similar[0]
    best = np.array(best)
    best = np.partial
    print(best)
    break

TypeError: 'NoneType' object is not iterable